---
title: Titan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  servicecategories:
    title: servicecategories
    output: true
baseurl: 
url: 
description: Titan is a professional cleaning service provider.
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
