title: Titan
baseurl: 
url: 
description: Titan is a professional cleaning service provider.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  servicecategories:
   title: servicecategories
   output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
